sys = require 'sys'
exec = (require 'child_process').exec

FILENAME = 'main'
FILES = [
	'main.coffee'
	'player.coffee'
]

task 'compile', "compile #{FILENAME}.", (options) ->
	outputErr = (err, stdout, stderr) ->
		throw err if err
		if stdout or stderr
			console.log "#{stdout} #{stderr}"
	if FILES.length is 1
		exec "coffee -c #{FILENAME} #{FILES[0]}", outputErr
	else
		exec "coffee -cj #{FILENAME} #{FILES.join ' '}", outputErr
		exec "echo #{FILES.join ' '}", outputErr
